linter:
  rules:
    #     # see catalog here: http://dart-lang.github.io/linter/lints/
    - hash_and_equals
    - prefer_equal_for_default_values

analyzer:
#   exclude:
#     - path/to/excluded/files/**